### ISSUE TITLE
Preselect a row

### ISSUE THREAD

**Issue by justdan0227** [jriosdev/iOSDropDown#10]
If I have 7 elements and I want the 3rd one pre-selected, I'm not seeing that method call.  I see Select and Select! but if I pass the exact text string in the drop down it does not appear?

**Comment by justdan0227** [comment]
Ok found that if I did this .. it selected what I wanted

            categoryDropDown.text = theGoalObject!.type
            categoryDropDown.select(theGoalObject!.type)

**Comment by jriosdev** [comment]
categoryDropDown.selectedIndex = some Index
it will work

**Comment by justdan0227** [comment]
I thought so too, however that won't work as it’s a setter.  "Cannot assign to property: 'selectedIndex' setter is inaccessible".

**Comment by jriosdev** [comment]
sorry for the late,
now I updated cocoa pod with changes

**Comment by justdan0227** [comment]
no worries.. Thanks.. I got around it by setting the text.. Will be great using index as well. Awesome utility!

**Comment by moizirshad** [comment]
```
dropdown.text = dropdown.optionArray[0]
dropdown.selectedIndex = 0
```
