### ISSUE TITLE
How to set iOSDropDown direction?

### ISSUE THREAD

**Issue by mazharulbelal** [jriosdev/iOSDropDown#104]
Sometimes the iOSDropDown list shows on top and sometimes shows to bottom. how can I handle it?

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @mazharulbelal 

You could check my SwiftyMenu for more stable and functionality reach menu.

[Search in Menu](https://www.linkedin.com/posts/karimebrahem_ios-swift-iosdevelopment-activity-6935131259824152578-FXLL?utm_source=linkedin_share&utm_medium=member_desktop_web) functionality is coming to SwiftyMenu very soon 😉

Check it out: https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu

Thank you.

**Comment by jriosdev** [comment]
mainDropDown.semanticContentAttribute = .forceRightToLeft 
  
  Added in New version

**Comment by kuldeep13990** [comment]
@mazharulbelal @jriosdev dropdown direction is always bottom. How can I change the dropdown direction to the top?
