### ISSUE TITLE
Selection is not working iOS 15+

### ISSUE THREAD

**Issue by nkollu** [jriosdev/iOSDropDown#105]

**Comment by nkollu** [comment]
I am unable to select the dropdown item in ios 15

**Comment by sudheer5013** [comment]
Same issue. I am unable to select the dropdown item in ios 15

**Comment by Guiraudou** [comment]
Same issue. Have you found a solution ?

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @nkollu , @sudheer5013 , @Guiraudou 

You could check my SwiftyMenu for more stable and functionality reach menu.

[Search in Menu](https://www.linkedin.com/posts/karimebrahem_ios-swift-iosdevelopment-activity-6935131259824152578-FXLL?utm_source=linkedin_share&utm_medium=member_desktop_web) functionality is coming to SwiftyMenu very soon 😉

Check it out: https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu

Thank you.

**Comment by Guiraudou** [comment]
It looks like a very good lib. When will it be available ?

**Comment by KarimEbrahemAbdelaziz** [comment]
@Guiraudou it's already available. Or you're asking about the `Search` functionality specifically ?

**Comment by Guiraudou** [comment]
Yes I'm asking about Search fonctionnality of course

**Comment by KarimEbrahemAbdelaziz** [comment]
@Guiraudou this update is coming today ;)

**Comment by Guiraudou** [comment]
Great !

**Comment by Guiraudou** [comment]
@KarimEbrahemAbdelaziz today (so yesterday now) you said ?

**Comment by Guiraudou** [comment]
@jriosdev Many thanks for the update :)
