### ISSUE TITLE
Adding search filter customization capability

### ISSUE THREAD

**Issue by scy0334** [jriosdev/iOSDropDown#108]
Hi! Thanks for this amazing library. 

I want to add a search functionality for Korean, but current search feature isn't compatible with Korean.

So I was wondering what if we add search feature customization for `iOS DropDown` as below.

**Current**
```
var searchText = String() {
        didSet{
            if searchText == "" {
                self.dataArray = self.optionArray
            }else{
                self.dataArray = optionArray.filter {
                    return $0.range(of: searchText, options: .caseInsensitive) != nil
                }
            }
            reSizeTable()
            selectedIndex = nil
            self.table.reloadData()
        }
    }
```

**My Suggestion**
```
 var searchText = String() {
        didSet{
            if searchText == "" {
                self.dataArray = self.optionArray
            }else{
                self.dataArray = optionArray.filter {
                    return searchFilter(text: $0, searchText: searchText)
                }
            }
            reSizeTable()
            selectedIndex = nil
            self.table.reloadData()
        }
    }
    
    open func searchFilter(text: String, searchText: String) -> Bool {
        return text.range(of: searchText, options: .caseInsensitive) != nil
    }
```

In this way, I can subclass `DropDown` and customize the searchFilter as my own need. 

Thanks!

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @scy0334 

You could check my SwiftyMenu for more stable and functionality reach menu.

[Search in Menu](https://www.linkedin.com/posts/karimebrahem_ios-swift-iosdevelopment-activity-6935131259824152578-FXLL?utm_source=linkedin_share&utm_medium=member_desktop_web) functionality is coming to SwiftyMenu very soon 😉

Check it out: https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu

Thank you.

**Comment by jriosdev** [comment]
Thanks for your suggestions, i will update it
