### ISSUE TITLE
How to set IOSDropDown item color

### ISSUE THREAD

**Issue by Vencer-Co** [jriosdev/iOSDropDown#109]
How to set IOSDropDown item color

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @Vencer-Co 

You could check my SwiftyMenu for more stable and functionality reach menu.

[Search in Menu](https://www.linkedin.com/posts/karimebrahem_ios-swift-iosdevelopment-activity-6935131259824152578-FXLL?utm_source=linkedin_share&utm_medium=member_desktop_web) functionality is coming to SwiftyMenu very soon 😉

Check it out: https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu

Thank you.

**Comment by jriosdev** [comment]
Dropdown.itemsColor = color
