### ISSUE TITLE
Behind text field is clicking during selection of dropdown item.

### ISSUE THREAD

**Issue by nishantapps** [jriosdev/iOSDropDown#13]
I am using multiple text field and i have added drop down in one text field after clicking on drop down text field, the text field behind the drop down is clicking thats why not able to click on drop down menu item

**Comment by stonekase** [comment]
Please. can you clarify on this **".If you are using Multiple Drop Downs in a Single ViewController, Must Kept reverse order on StoryBoard"** it seems to confuse me and I am having the same issue. @jriosdev

**Comment by jriosdev** [comment]
sorry for the delay and poor english 
![screen shot 2018-10-11 at 3 07 38 pm](https://user-images.githubusercontent.com/38908155/46795327-8286d480-cd67-11e8-9894-4656615c4acd.png)

I mean like this,
if you have multiple dropdowns 1, 2, 3, 4... 
normally in our storyboard elements in the same order
we want to revers like the photo 
to avoid overlaying

**Comment by stonekase** [comment]
I have tried this but it seems , the dropdown isn't receiving input at all.

<img width="525" alt="screen shot 2018-10-11 at 1 29 24 pm" src="https://user-images.githubusercontent.com/5037778/46804881-aba16800-cd5b-11e8-9d5e-0872ef6a0f40.png">
<img width="509" alt="screen shot 2018-10-11 at 1 44 47 pm" src="https://user-images.githubusercontent.com/5037778/46804997-ee634000-cd5b-11e8-8a71-e5caa062b33a.png">
![Uploading Screen Shot 2018-10-11 at 1.44.55 PM.png…]()
![Uploading Screen Shot 2018-10-11 at 1.44.28 PM.png…]()

**Comment by stonekase** [comment]
<img width="282" alt="screen shot 2018-10-11 at 1 44 55 pm" src="https://user-images.githubusercontent.com/5037778/46805104-37b38f80-cd5c-11e8-9974-20bff8d81f10.png">

**Comment by jriosdev** [comment]
> I have tried this but it seems , the dropdown isn't receiving input at all.
> 
> <img alt="screen shot 2018-10-11 at 1 29 24 pm" width="525" src="https://user-images.githubusercontent.com/5037778/46804881-aba16800-cd5b-11e8-9d5e-0872ef6a0f40.png">
> 
> <img alt="screen shot 2018-10-11 at 1 44 47 pm" width="509" src="https://user-images.githubusercontent.com/5037778/46804997-ee634000-cd5b-11e8-8a71-e5caa062b33a.png">
> 
> ![Uploading Screen Shot 2018-10-11 at 1.44.55 PM.png…]() ![Uploading Screen Shot 2018-10-11 at 1.44.28 PM.png…]()

which type of input, You mean?

**Comment by stonekase** [comment]
the dropdown textfield shown in the first image I uploaded (the one in the emulator), it doesn't receive clicks .I implemented the click listener but it doesn't. see code below
<img width="864" alt="screen shot 2018-10-11 at 2 37 47 pm" src="https://user-images.githubusercontent.com/5037778/46808117-7436b980-cd63-11e8-8e26-cc2da76e6724.png">

**Comment by jriosdev** [comment]
can u please give example  source code with storyboard , i will check , what is the issue you having

**Comment by stonekase** [comment]
[Archive.zip](https://github.com/jriosdev/iOSDropDown/files/2469278/Archive.zip)


please see attached

**Comment by jriosdev** [comment]
I checked your code , but i didn't saw any thing wrong,
So you just try without input accessory view or the popup pod
It may works

**Comment by stonekase** [comment]
wow, and the popup is necessary due to design restrictions

**Comment by jriosdev** [comment]
Is the issue with popup?

**Comment by jriosdev** [comment]
Try to create simple popup

https://youtu.be/WnlPZbSnlLI

**Comment by stonekase** [comment]
ok let me look at the link, try it and give a feedback

**Comment by hamoti71** [comment]
Hi 
I had the same problem and it's fix is put in viewDidLoad the following:
childView.superview?.bringSubviewToFront(childView)

**Comment by mohsinka** [comment]
My DropDown TextFields were in StackView, upon removing them from StackView solved the problem for me.

**Comment by sampsonliao** [comment]
This is still an issue that can EASILY be tested. create an Tap Gesture Recognizer and place it on the view. When you select from the DropDown, the tap gesture gets triggered. Clearly not intended.

**Comment by jriosdev** [comment]
Please update your code
issue solved thanks
