### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by alejantab** [jriosdev/iOSDropDown#16]
How can i remove the bounce animation? it is slow when is closing the table after choose the option.

**Comment by jriosdev** [comment]
there is no way to remove animation , sorry

**Comment by gunantosteven** [comment]
you can remove the bounce animation actually, In DropDown.swift change all the UIView.animate to withDuration: 0.0 and delay: 0.0 would fix it.

**Comment by iosdroid** [comment]
> you can remove the bounce animation actually, In DropDown.swift change all the UIView.animate to withDuration: 0.0 and delay: 0.0 would fix it.


can you give the example

**Comment by gunantosteven** [comment]
> > you can remove the bounce animation actually, In DropDown.swift change all the UIView.animate to withDuration: 0.0 and delay: 0.0 would fix it.
> 
> can you give the example

you can check my latest commit iOSDropDown repository. I have forked it.

**Comment by iosdroid** [comment]
> > > you can remove the bounce animation actually, In DropDown.swift change all the UIView.animate to withDuration: 0.0 and delay: 0.0 would fix it.
> > 
> > 
> > can you give the example
> 
> you can check my latest commit iOSDropDown repository. I have forked it.

Thank you got it
