### ISSUE TITLE
OverLap with the parentView Context

### ISSUE THREAD

**Issue by ShaikBaji1911** [jriosdev/iOSDropDown#18]
Hello, I have an issue like for example I have an button below the Textfield(iOS drop down) when I click textfield my drop down will be opened and let us assume that I have 3 Contents inside the Dropdown and when I click the first content the button which is beneath the textfield is being selected so how to overcome this issue and one more when I have a content below my textfield when I click textfield (dropdown) my dropdown opens but it is not displaying over it (It means I was able to see my content and dropdown content mixed ) how to resolve these 2 issues please clear about it

**Comment by ShaikBaji1911** [comment]
Hello Brother the idea which u said works fine but in tableview cell it is
not working bro even though I placed in last position  u can see below the
answer duration textfield it went down of it please help me brother  may I
have your contact number please
[image: Screen Shot 2018-10-30 at 11.58.47 AM.png]

**Comment by ShaikBaji1911** [comment]
yes it works fine when I placed it reverse order or when I assign my TF last but I have a problem when I works in Tableview cell  the dropdown goes below the cell I mean it is not visible  can I have your personal email jriosdev please to send my screenshot so that you can get an idea please help me

**Comment by jriosdev** [comment]
Can you send screenshot to me

**Comment by ShaikBaji1911** [comment]
Can I have your personal email id brother so that I can send you reply me
asap

**Comment by jriosdev** [comment]
jriosdev@gmail.com

**Comment by mariamismail** [comment]
"I have a problem when I works in Tableview cell the dropdown goes below the cell I mean it is not visible "
 ia have the same problem when dequeue the cell the dropdown goes below the cel

**Comment by ShaikBaji1911** [comment]
Yeah, even I have the same problem like when I am using  customCell in TableView  the dropDown list is not visible it gets hidden beneath the TableViewCell please help asap the rest of this pod is super and great @jriosdev hope you fix this issue soonly

**Comment by KingOlami** [comment]
I have the same issue. any fix 
![simulator screen shot - iphone xr - 2018-11-27 at 20 08 20](https://user-images.githubusercontent.com/22158320/49105211-4c060a00-f280-11e8-9b4c-d1064fc88abe.png)

**Comment by MichaelRSilva** [comment]
Hello,

I have the same problem whit @SogoGolf  I can get the dropdown to display over the top of other controls - however when i tap on any of the dropdown rows, the tap is not recognised.

**Comment by rmvz3** [comment]
Nice, nice, control. I love it but, unfortunately, I'm facing the same problem as Michael. I have it added to a stackview. I managed to make it visible by iterating the others arrangedViews, sending them to back and setting their isUserInteractionEnabled flag to false to avoid unwanted touches but the real problem is when the DropDown opens it does it outside of the current arrangedView and then it doesn't get touches anymore.

I've tried to make every single view multi-touch, force dropDown to be the first responder, etc...

**Comment by Abdulmoiz-Ahmer** [comment]
> Nice, nice, control. I love it but, unfortunately, I'm facing the same problem as Michael. I have it added to a stackview. I managed to make it visible by iterating the others arrangedViews, sending them to back and setting their isUserInteractionEnabled flag to false to avoid unwanted touches but the real problem is when the DropDown opens it does it outside of the current arrangedView and then it doesn't get touches anymore.
> 
> I've tried to make every single view multi-touch, force dropDown to be the first responder, etc...

did you find any solution

**Comment by Abdulmoiz-Ahmer** [comment]
> thanks for this nice component. I'm having same problem. i can get the dropdown to display over the top of other controls - however when i tap on any of the dropdown rows, the tap is not recognised.

did you resolve it somehow.

**Comment by nirojan0930** [comment]
Did you guys find any solution to 

> thanks for this nice component. I'm having same problem. i can get the dropdown to display over the top of other controls - however when i tap on any of the dropdown rows, the tap is not recognised.

Did you guys find any solution for this issue?

**Comment by SogoGolf** [comment]
https://github.com/AssistoLab/DropDown

**Comment by jriosdev** [comment]
Please Update your code 
Issue solved 
Thanks

**Comment by haripatel-mobio** [comment]
I am also facing the same issue

I have made modifications to the iOSDropDown.swift class by manually updating the code.

> 1. Adding a Method to Find the Superview

I created a new method to find a specific type of superview in the view hierarchy:
```
func findViewInHierarchy<T: UIView>(startingFrom view: UIView, ofType type: T.Type) -> T? {
    var currentView: UIView? = view
    
    while let view = currentView {
        // Check if the current view matches the desired type
        if let matchedView = view as? T {
            return matchedView
        }
        // Move to the next parent view
        currentView = view.superview
    }
    
    // Return nil if the desired view is not found
    return nil
}
```

> 2. Updating the parentView Property

I used the new method to identify the parent view where the dropdown should be displayed and assigned it to the parentView property:

```
if let superview = findViewInHierarchy(startingFrom: self, ofType: [YourParentView].self) {
    print("Found the LayoverView!")
    dropDown.parentView = superview
} else {
    print("LayoverView not found in hierarchy.")
}
```

> 3. Changes in the DropDown Class

To accommodate the above, I replaced the parentController property with parentView in the DropDown class. Here’s the modified code for the showList() function:

```
open class DropDown: UITextField {
    @IBInspectable public var parentView: UIView?

    public func showList() {
        Log.testPrint("TAG: \(self.tag)")
        
        // Ensure parentView is set
        if parentView == nil {
            parentView = self.superview
        }

        backgroundView.frame = parentView?.frame ?? backgroundView.frame
        pointToParent = getConvertedPoint(self, baseView: parentView)
        parentView?.insertSubview(backgroundView, belowSubview: self)

        // Display the dropdown table
        TableWillAppearCompletion()
        tableheightX = min(listHeight, rowHeight * CGFloat(dataArray.count))
        
        table = UITableView(frame: CGRect(x: pointToParent.x,
                                          y: pointToParent.y + self.frame.height,
                                          width: self.frame.width,
                                          height: tableheightX))
        shadow = UIView(frame: table.frame)
        shadow.backgroundColor = .clear

        table.dataSource = self
        table.delegate = self
        table.separatorStyle = .none
        table.layer.cornerRadius = 3
        table.backgroundColor = rowBackgroundColor
        table.rowHeight = rowHeight

        parentView?.addSubview(shadow)
        parentView?.addSubview(table)
        
        // Handle dropdown animation
        let availableHeight = (parentView?.frame.height ?? 0) - (pointToParent.y + frame.height + 5)
        var dropdownY = pointToParent.y + frame.height + 5
        if availableHeight < (keyboardHeight + tableheightX) {
            dropdownY = pointToParent.y - tableheightX
        }

        UIView.animate(withDuration: 0.9,
                       delay: 0,
                       usingSpringWithDamping: 0.4,
                       initialSpringVelocity: 0.1,
                       options: .curveEaseInOut,
                       animations: {
                           self.table.frame = CGRect(x: self.pointToParent.x,
                                                     y: dropdownY,
                                                     width: self.frame.width,
                                                     height: self.tableheightX)
                           self.table.alpha = 1
                           self.shadow.frame = self.table.frame
                           self.shadow.dropShadow()
                           self.arrow.position = .up
                       },
                       completion: { _ in
                           self.layoutIfNeeded()
                       })
    }
}
```

Make sure to updated everywhere the dropdown logic to use parentView instead of parentController
