### ISSUE TITLE
DidSelect of table not calling

### ISSUE THREAD

**Issue by umairgillaniucp** [jriosdev/iOSDropDown#19]
i have a view inside which i have placed a textfield. My drop down have 3 items, when drop down is visible only 1st item calls didselect method other two don't call the didselect method. My assumption is that the other two methods are out of the bound of parent view because when i increased the height of parent view for testing the didselect method called for all three items. 

any quick fix for the issue?

**Comment by jriosdev** [comment]
just do drop down 
bringSubviewToFront(button)

**Comment by umairgillaniucp** [comment]
tried this but it did not help me out.

**Comment by jriosdev** [comment]
there is another way is increate the parent view size when clicking 
listWillAppear() {
  //You can Do anything when iOS DropDown willAppear 
 }

listDidAppear() {
    //You can Do anything when iOS DropDown listDidAppear
}

listWillDisappear() {
  //You can Do anything when iOS DropDown listWillDisappear 
}

 listDidDisappear() {
  //You can Do anything when iOS DropDown listDidDisappear
}


this closures may help you

**Comment by umairgillaniucp** [comment]
ye increase view height can help me but it will disturb the ui it not looks good that when popup appear vie's height increase with that

**Comment by umairgillaniucp** [comment]
hmmm, thanks i will modify it according to my need. Overall it's really good 👍
