### ISSUE TITLE
Item list shows behind other elements

### ISSUE THREAD

**Issue by mahdimirzaei1** [jriosdev/iOSDropDown#21]
I use dropdown inside a vertical stack and when i tap dropdown its list shows behind other textfields. I tried to use bringSubview() but it didn't work.
Any solution?

**Comment by AbanoubNabil** [comment]
list the textFields in reversed order in story board see https://github.com/jriosdev/iOSDropDown/issues/13

**Comment by jriosdev** [comment]
Thanks for the reply @AbanoubNabil
