### ISSUE TITLE
Changing text color of rows

### ISSUE THREAD

**Issue by codyrotwein** [jriosdev/iOSDropDown#23]
How can I change the text color of the rows? I tried using interface builder, as well as programmatically, but the text color stays black.

**Comment by jriosdev** [comment]
Tomorrow I will add  text color property to rows ,

**Comment by lehanphong** [comment]
How can I change the text color of the rows? help me!!!

**Comment by jimmy510s** [comment]
i am a bit late but you can do something like this pod 'iOSDropDown', :git => 'https://github.com/jriosdev/iOSDropDown', :commit => 'c7ee7e9'
