### ISSUE TITLE
Arrow color

### ISSUE THREAD

**Issue by Lukas182** [jriosdev/iOSDropDown#25]
Any way to change the arrow color?

**Comment by jriosdev** [comment]
currently no. but, i will update soon

**Comment by horaciosolorio** [comment]
Will be grate algo can change custom image for arrow

**Comment by appsportfolio** [comment]
any way to update arrow . color ?

**Comment by mohsinka** [comment]
Any way to change Arrow Image?

**Comment by AsadJavid** [comment]
to change arrow color you can change shape layer's fill color in **iOSDropDown.swift** class where it is drawing the arrow.
![Screenshot 2019-05-12 at 8 36 06 AM](https://user-images.githubusercontent.com/32340906/57577478-35034f00-7491-11e9-8612-3b7981a2e9dd.png)

**Comment by jriosdev** [comment]
Updated
