### ISSUE TITLE
`selectedIndex` does not Fill the box

### ISSUE THREAD

**Issue by MrBenFTW** [jriosdev/iOSDropDown#27]
`selectedIndex` selects the right option, but it does not fill Option 1 into the text box.

**Comment by engali94** [comment]
How did you solve this?

**Comment by masgarifor2** [comment]
Hi, you can fill textBox with `text` property and after that set `selectedIndex`

` self.myDropDown.text =  "Test Itam"
 self.myDropDown.selectedIndex = 0`

**Comment by jriosdev** [comment]
@masgarifor2  Thanks for the replay
