### ISSUE TITLE
How to Delegate

### ISSUE THREAD

**Issue by MrBenFTW** [jriosdev/iOSDropDown#28]
Hello, I am using this to select servers: [example](https://imgur.com/a/SxZpvgk)

When I select `Germany 1` I want to `UserDefaults.standard.set("1.1.1.1", forKey: "IP")`

When I select `Germany 2` I want to `UserDefaults.standard.set("8.8.8.8", forKey: "IP")`

How can I do this?

**Comment by jriosdev** [comment]
dropDown.didSelect{(selectedText , index ,id) in
  if selectedText ==  "Germany 1"{
        UserDefaults.standard.set("1.1.1.1", forKey: "IP")
    }
}
