### ISSUE TITLE
drop down list show behind text field 

### ISSUE THREAD

**Issue by rajkumar0143** [jriosdev/iOSDropDown#29]
![image1](https://user-images.githubusercontent.com/35296341/50833684-13297c80-1378-11e9-97b1-5a901f678f28.png)

**Comment by AdrenalineAMP** [comment]
Have to rearrange your storyboard, see [``](https://github.com/jriosdev/iOSDropDown/issues/5#issuecomment-418731445)

**Comment by AdrenalineAMP** [comment]
Have to rearrange your storyboard, see [](https://github.com/jriosdev/iOSDropDown/issues/5#issuecomment-418731445)

**Comment by AdrenalineAMP** [comment]
See issue #5 in the closed section:
[https://github.com/jriosdev/iOSDropDown/issues/5#issuecomment-418731445](url)

**Comment by Ahyox** [comment]
Please as this issue been fixed? Im having the same issue. Thanks

**Comment by jriosdev** [comment]
Please update the code 
issue has been solved 
Thank you
