### ISSUE TITLE
DropDown list is not tapable

### ISSUE THREAD

**Issue by Abdulmoiz-Ahmer** [jriosdev/iOSDropDown#30]
For the visibility on the bottom view i reversed the order in the storyboard and as a result the dropdown is visible on the below view but as a side effect the drop down is now unselectable. How can i fix this.

**Comment by nizzam** [comment]
What the solution for this ?

**Comment by Abdulmoiz-Ahmer** [comment]
Couldnot fixed it brother. I used a uitableview instead.

**Comment by nirojan0930** [comment]
i'm also facing the same issue. Did you find any solution?

**Comment by jriosdev** [comment]
Issue solved Please Use new update of the code 
thanks

**Comment by rathodmayur93** [comment]
Still facing the same issue.
Unable to click on the dropdown list

**Comment by jackantico1** [comment]
I'm having the issue as well. Any luck solving?
