### ISSUE TITLE
detect focusChanges

### ISSUE THREAD

**Issue by deepakverma4** [jriosdev/iOSDropDown#32]
I am just a beginner in swift. and have  following query

I have 3 iosDropDown field and 3 uitextfield. all i want is to focus only 1 textfield/iosdropdown at a time. like when i search on 1st dropdown i want 2nd dropdown list to hide. how can i do that?

**Comment by smarthersm22** [comment]
FirstDropDown.listWillAppear
{
SecondDropDown.ishidden = true 
}

**Comment by gowthamSakthi** [comment]
FirstDropDown.listWillAppear
{
secondDropDown.ishidden = true
}

**Comment by mohsinka** [comment]
or

```
secondDropDownList.isSelected == true {
    secondDropDownList.hideList()
}
```
