### ISSUE TITLE
Images list

### ISSUE THREAD

**Issue by VictorUrielP** [jriosdev/iOSDropDown#34]
Is it possible to add images to the list? Or is there is some way to customize each row? 

I am trying to achieve something like this:

![whatsapp image 2019-02-13 at 11 29 42 pm](https://user-images.githubusercontent.com/29692881/52764853-4dc1ad00-2fe7-11e9-9740-f350b87598b8.jpeg)

Thank you!

**Comment by jriosdev** [comment]
https://github.com/jriosdev/iOSDropDown/blob/03f3263c170d5a61de55a50a240d2ecfd4812e37/iOSDropDown/Classes/iOSDropDown.swift#L314

just add a line
cell.imageview.image = yourImages[indexPath.row]

it will work

**Comment by VictorUrielP** [comment]
I added this three lines at the top

```
fileprivate  var imageArray = [String]()

public var optionImageArray = [String]() {
        didSet{
            self.imageArray = self.imagePerOptionArray
        }
}
```
Then I added this line at 319 as you suggested:

```cell!.imageView!.image = UIImage(named:imageArray[indexPath.row])```

And finally, in my ViewController I just called:

```
self.radiusList.optionArray = ["Option 1", "Option 2", "Option 3", "Option 4"]
self.radiusList.imagePerOptionArray = ["image1", "image2", "image3", "image4"]
```
And it worked. ¡Thank you!

I will close this issue.

**Comment by VictorUrielP** [comment]
I created a pull request about this topic. Hope you can take it into account. It is validated but if you think it needs more validation I can add it too.
