### ISSUE TITLE
when there is another component or view after this drop down list will goes under that view and user not able to click it

### ISSUE THREAD

**Issue by SaurabhCloudAnalogy** [jriosdev/iOSDropDown#49]
![Screenshot 2019-08-22 at 3 17 30 PM](https://user-images.githubusercontent.com/48583524/63504894-23016580-c4f0-11e9-9e25-8c62d1d4d439.png)

**Comment by jriosdev** [comment]
https://github.com/jriosdev/iOSDropDown/issues/13#issuecomment-428890576

**Comment by SaurabhCloudAnalogy** [comment]
Thanks
