### ISSUE TITLE
Dropdown is behind 

### ISSUE THREAD

**Issue by justdan0227** [jriosdev/iOSDropDown#5]
What am I missing that when the drop down appears it goes behind other controls that are on the view.  Doing this all with Storyboard ios11

**Comment by justdan0227** [comment]
yeah I'm so sorry.. I read that and didn't understand.. then I looked at the demo.  Moved my drop downs to the bottom of the list in IB and bingo.  Works awesome!  Thanks!

**Comment by knight6700** [comment]
but in stackView how can make it in bottom

**Comment by iSevenDays-waverley** [comment]
Yes, there is no good solution when using stackView

**Comment by iSevenDays-waverley** [comment]
A quick fix:
-self.superview?.insertSubview(table, belowSubview: self)
+self.superview?.addSubview(table)

**Comment by knight6700** [comment]
which table ?
