### ISSUE TITLE
Multiples

### ISSUE THREAD

**Issue by justdan0227** [jriosdev/iOSDropDown#6]
What is meant by (if using storyboard): 

"1.If you are using Multiple Drop Downs in a Single ViewController, Must Kept reverse order on StoryBoard or addSubview()  to avoid Overlaying"

**Comment by jriosdev** [comment]
storyboard elements order, if you what drop down above of all elements, just rearrange

**Comment by jriosdev** [comment]
![screen-shot-2017-02-10-at-1 14 13-pm-1024x574](https://user-images.githubusercontent.com/38908155/45095130-eb60a880-b13a-11e8-8533-c0f144fbfe12.png)

**Comment by justdan0227** [comment]
Ahhh so all dropdowns have to be at the bottom of your IB order.  Got it.. Thanks!

**Comment by ajinkya92** [comment]
I have got it in the stack View and then the drop down click stops working.

**Comment by jriosdev** [comment]
it wont work with stack view now

**Comment by ajinkya92** [comment]
There is one more issue and that's when there is an additional text field
which is a normal text field every thing gets message up when I am making
the normal textfield delegate as self. Drop downs show and hide for no
reason.

**Comment by jriosdev** [comment]
specify on your delegate


if textField == yourtextField{
 do what you want
}
