### ISSUE TITLE
`selectedIndex` is not reset when `optionArray` is changed

### ISSUE THREAD

**Issue by thanhson13** [jriosdev/iOSDropDown#7]
Here the steps to reproduce the issue:
1. Set `optionArray` with `["One", "Two", "Three"]`
2. Select the "One", the `selectedIndex` is now `0`
3. Change `optionArray` to `["Three", "Two", "One"]`, the `selectedIndex` is still `0`. When open the list of dropdown, it show "Three" as selected text

**Comment by jriosdev** [comment]
Can you please elaborate your issue?

**Comment by thanhson13** [comment]
@jriosdev updated

**Comment by jriosdev** [comment]
`seletedIndex` is  the index of the item , if you want to do like this use `optionsIds`
1. Set optionArray with ["One", "Two", "Three"]
2.set optionids with [1,2,3] or what you need

if you want to change the order of optionArray , change optionIds correspondingly
