### ISSUE TITLE
Pre selected value

### ISSUE THREAD

**Issue by Muhitun** [jriosdev/iOSDropDown#75]
Hello, in the description of the library it is written that selectedIndex can be used to set value. But it is not accessible. It shows selectedindex setter is inaccessible. Can you please help me with this issue as I need to set a value returned from api in the search box.

**Comment by reefwing** [comment]
A work around for this issue is to set the text box directly and then the selected index (which does work for the check mark). For example:

```
dropDown.text = "Selected Text"
dropDown.selectedIndex = 0
```

**Comment by Muhitun** [comment]
Thanks for the help but still didn't work. I wrote the two lines you mentioned in the return function of my api call and still shows Cannot assign to property: 'selectedIndex' setter is inaccessible

**Comment by jriosdev** [comment]
: 'selectedIndex' setter is  now accessible
