### ISSUE TITLE
Still have memory leak that was fixed in February

### ISSUE THREAD

**Issue by randyhill** [jriosdev/iOSDropDown#82]
This is a weird one that might be related to my limited experience with CocoaPods.  I am using iOSDropdown in my pods file as:

 pod 'iOSDropDown'

And regularly Pod Install & Pod Update. 

Yet I'm having a memory leak that's causing my viewcontroller not to be released that only occurs when I tap on a dropdown.  I saw this recent fix (#67)  

https://github.com/jriosdev/iOSDropDown/commit/4879d8160d8b999ef913f9479d251903b8ac41d3

and compared it to iosDropDown.swift in my iOSDropdown pod, I don't have the fix. I ran Pod Install and Pod Update both, neither time was iOSDropDown.swift updates. When I unlock the file and fix it manually, my memory leak goes away.

 Is there something I'm doing wrong to not get the latest iOSDropDown pod files?

**Comment by jriosdev** [comment]
i updated pod file
