### ISSUE TITLE
Dropdown get hide behind the keyboard

### ISSUE THREAD

**Issue by TejasPareek** [jriosdev/iOSDropDown#93]
when we click on the dropdown then the keyboard is open but it hides the dropdown items.
Any help would be grateful.
![Simulator Screen Shot - iPhone 6s - 2020-12-08 at 13 24 37](https://user-images.githubusercontent.com/38721916/101456081-86b7d800-3959-11eb-9342-42db7ef15067.png)
![Simulator Screen Shot - iPhone 6s - 2020-12-08 at 13 24 44](https://user-images.githubusercontent.com/38721916/101456090-8a4b5f00-3959-11eb-8540-c5d5cbbf42b0.png)

**Comment by jriosdev** [comment]
Use iOS dropDown Pod
it will work

**Comment by kuldeep13990** [comment]
Hi @jriosdev 
Could you please give the Pod name again.
