### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=2, address=0x6000028fb124)

### ISSUE THREAD

**Issue by sdiik** [jriosdev/iOSDropDown#98]
sir, I have problem with implementation on tableviewCell xib,
![Screen Shot 2021-03-01 at 13 03 10](https://user-images.githubusercontent.com/17142848/109458117-c7257e80-7a8e-11eb-8055-4fe6b1b34b3b.png)

can you help me sir ?

**Comment by meryemsahin** [comment]
Hi, i had this problem too. Can you check your textfield? Problem solved when i fixed it like this ->
![Screen Shot 2021-07-29 at 4 00 10 PM](https://user-images.githubusercontent.com/45317271/127496527-87b54754-b0e6-4907-ae3a-11a63cfc0ade.png)

**Comment by gupta163** [comment]
still getting same problem. ios12
